connect-foundation/2019-21

backend/.env
backend/.gitignore
backend/docker/docker-product.yml
backend/docker/dockerfiles/.dockerignore
backend/docker/dockerfiles/node.Dockerfile
backend/express/app.js
backend/package.json
backend/script/build-docker-image.sh
backend/yarn.lock

related issue 
#75 #79 
* 배포 자동화를 위한 수동 배포 세팅 설정
* [임시 배포 링크](http://106.10.53.159:3000/)
* hello 가 나오면 성공
* able to deploy express server 
* able to build docker image of node
* image has installed packaged
*add run script
docker:build -> build docker image
if package.json and yarn.lack are cached, it will skip build
docker:build:force -> force to build docker image
docker:start -> start docker by docker compose as demon
docker:stop -> stop docker containers
docker:clean -> clean created docker image
* add morgan for dev logger express server
* add gitignore setting
docke/cheched/*

env: 수동 배포 설정 추가

---

docs/클라우드 서버 기본 및 배포 설정.md

#82 
[wiki 링크](https://github.com/connect-foundation/2019-21/wiki/%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C-%EC%84%9C%EB%B2%84-%EA%B8%B0%EB%B3%B8-%EB%B0%8F-%EB%B0%B0%ED%8F%AC-%EC%84%B8%ED%8C%85)

docs: add 클라우드 서버 기본 및 클라우드 세팅 문서

---

backend/DB/migrations/20191114022801-create-like.js
backend/DB/migrations/20191114085344-add-association-like.js
backend/DB/models/guest.js
backend/DB/models/like.js
backend/DB/models/question.js
backend/DB/queries/event.js
backend/DB/utils.js
backend/express/app.js

#96 
DB 스키마 관계를 재설정하고 그에 따른 마이그레이션 파일 및 시더 파일 수정
기능구현에 필요한 api를 정의하고 엔드포인트를 정의

DB - 스키마 설계 재정의 및 migration,seeder 수정, api 추가 #96

---

frontend/main-app/src/App.js

이전 PR에서 반영되었어야 하는데, 미처 확인하지 못하고 다시 PR함

fix(main-app): 폴더 이름을 변경에 따라 컴포넌트 import 함께 변경함

---

frontend/guest-app/src/App/App.js
frontend/guest-app/src/components/TabGroup/TabGroup.js

#145 #147 
fix pollcontainer component location

hotfix: resolve merge conflict #145 #147

---

frontend/host-app/src/components/HeaderConfigAvata.js
frontend/host-app/src/components/Poll/NewPollModal.js
frontend/host-app/src/components/Questions/QuestionContainer.js

QuestionContainer에 modal hook과 Button을 생성하여 NewPollModal과 연결하여 버튼을 클릭했을 때 모달 팝업이 뜰수있도록 구현.

fix: host app 투표만들기 버튼이 없어서 투표만들기 모달창을 못띄우는 문제 해결

---

frontend/guest-app/src/components/Poll/ActiveRating.js
frontend/guest-app/src/components/Poll/Item.js
frontend/guest-app/src/components/Poll/PollCard.js
frontend/guest-app/src/components/Poll/PollContainer.js
frontend/guest-app/src/components/Poll/PollDummyData.js
frontend/guest-app/src/components/Poll/RatingItem.js
frontend/guest-app/src/components/Poll/SelectionItems.js

merge conflict resolve from feature/guest-poll-state

---

frontend/guest-app/src/components/Emoji/EmojiArea.js
frontend/guest-app/src/components/Question/QuestionCard/QuestionCard.js

hotfix: fix import path of guest-app

---

frontend/host-app/src/components/Poll/DateItems.js
frontend/host-app/src/components/Poll/NewPollModal.js
frontend/host-app/src/components/Poll/PollName.js
frontend/host-app/src/components/Poll/RatingBlock.js
frontend/host-app/src/components/Poll/TextItems.js

refactoring: Host-app 투표생성 모달

---

backend/express/app.js
backend/package.json
backend/yarn.lock

프로젝트에 socket.io 를 적용하기 위해 연습 코드를
push

add: socket-io 연습 코드

---

backend/express/app.js
backend/package.json
backend/socket_io_server/app.js
backend/socket_io_server/config/configLoader.js
backend/socket_io_server/config/socket.dev.config.js
backend/socket_io_server/config/socket.prod.config.js
backend/socket_io_server/config/socket.test.config.js
backend/yarn.lock
frontend/guest-app/package.json
frontend/guest-app/src/components/Question/QuestionCard/QuestionCardHeader.js
frontend/guest-app/src/components/Question/QuestionContainer.js
frontend/guest-app/src/index.js
frontend/guest-app/src/socket.io-Client-wrapper.js
frontend/guest-app/yarn.lock

#184 
어제 페어프로그래밍으로 작성한 함수들을 활용하여
질문 실시간 추가 기능에 대한 base code 를 작성

add: question tab - 질문 추가 baseCode #184

---

frontend/guest-app/package.json
frontend/guest-app/src/components/Emoji/EmojiArea.js
frontend/guest-app/yarn.lock

@material-ui/icons 패키지 추가
Emoji 추가 버튼을 <IconButton> 형식으로 변경

guest-app/Emoji

---

frontend/guest-app/src/components/Poll/SelectionItems.js

fix: 추가로 입력된 <Item /> 제거

---

frontend/guest-app/src/components/Emoji/EmojiArea.js
frontend/guest-app/src/components/Emoji/EmojiDummyData.js
frontend/guest-app/src/components/Emoji/EmojiInstance.js

해당 이모지를 click 하면
이전에 내가 클릭했는지 여부를 확인하여 count를 + 또는 - 함
만약, 나만 클릭한 이모지인 경우, 다시 클릭하면 삭제됨

guest-app / Emoji onClick 핸들러 추가

---

frontend/guest-app/src/components/Emoji/EmojiArea.js

Emoji 객체에 있는 id를 직접 .length, map(index)등을 이용하여 다시 추가함

fix(guest-app/Emoji): 내가 추가한 이모지를 다시 클릭하면 내가 추가한 모든 이모지가 삭제되는 현상 수정

---

frontend/guest-app/src/components/Question/QuestionContainer.js
frontend/guest-app/src/libs/socket.io-Client-wrapper.js

증상
첫 질문만 추가되고 그다음 질문이 추가되지 않음
해결
useEffect dependency 에 관찰할 state 추가
socket.io handler가 중첩되지 않도록 등록하기전 이전 핸들러를 모두 해제함

hotfix: react socket.io custom hook의 버그 수정

---

backend/DB/models/emoji.js
backend/DB/queries/event.js
backend/graphQL/model/question/question.graphql
backend/graphQL/model/question/question.resolver.js

getQuestionsInEvent 함수를 통해 graphql 이
동작할 수 있도록 fix
warning:: graphql 과 sequelize 사이의 속성 이름 명세 뒤죽박죽, 수정필요

fix: graphql hotfix #231 #238

---

backend/graphQL/model/question/question.graphql
backend/graphQL/model/question/question.resolver.js
frontend/guest-app/src/components/Question/QuestionContainer.js

sequelize 에서 사용하는 createdAt 라는 이름과
graphql 에서 사용하는 Date 의 이름이 달라
오류가 발생해서 수정

fix: graphql 스키마 변경 Date -> createdAt

---

frontend/guest-app/src/components/Emoji/CustomEmojis.js
frontend/guest-app/src/components/Emoji/EmojiPickerModal.js

- Custom emoji 추가
- 깃허브 및 앵무새, 고양이, 스피드 메탈 모션 이모지 추가
- Emoji-mart 라는 타이틀을 "Pick your emoji..."으로 변경

enhance: Custom emoji 추가, Emoji-mart 타이틀 변경

---

frontend/guest-app/scripts/start.js
frontend/host-app/scripts/start.js
frontend/main-app/scripts/start.js

기본 3000 포트에서 5000대 포트로 변경
main-app 5000
host-app 5001
guest-app 5002

env: react app dev server port 변경

---

frontend/host-app/src/components/Questions/QuestionDate.js

DB 에 저장된 date(createdAt) 의 형식이 바뀌어 오류가 발생하여
이를 수정함

fix: host-app "slice" 오류 해결

---

backend/DB/migrations/20191112070321-create-event.js
backend/DB/models/event.js
backend/DB/queries/event.js
backend/DB/utils.js
backend/graphQL/app.js
backend/graphQL/model/hostpage/hostpage.resolver.js

createEvent추가
updateEventById추가
getEventByHost 이름 변경
getEventByHost -> getEventByHostId

feature: event model DB query api 추가 & 이름 변경

---

backend/express/routes/auth.js
backend/graphQL/app.js
frontend/host-app/src/App/App.js

main->host Oauth 리다이렉트시 포트 변경되어
제대로 이동하지 않는 문제 해결
resolver 에 주석때문에 host-app 이제대로 동작하지 않는
문제 해결

fix: host-app 켜지지 않는 문제 해결

---

backend/DB/models/hashtag.js

hotfix: hashTag 연관 관계 수정

---

backend/DB/queries/hashtag.js
backend/DB/queries/hashtag.spec.js

* hashtag table을 위한 DB 쿼리 api 추가
***warning***
* 단순한 테스트가 추가됨 mocha unit test 로 리펙토링이 필요함

feature: hashtag DB query api with naive test code

---

package.json
script/start.sh
yarn.lock

env: 최상위 폴더에서 yarn start 로 front, back 둘다 dev mode 로 실행하는 yarn run script 추가

---

frontend/guest-app/src/components/Emoji/CustomEmojis.js
frontend/guest-app/src/components/Question/QuestionCard/QuestionCardHeader.js
frontend/main-app/src/components/LoginModal.js

lint 오류로그가 너무 많아
frontEnd 파일에 lintFix 적용

fix: lint FE

---

backend/graphQL/model/question/question.resolver.js

questions: (_, {eventCode},{guestId}) =>
questions: (_, {eventCode, guestId})
인자 위치가 잘못되어 오류 발생

fix: question.resolver.js

---

backend/DB/dummy/initialConfig.js
backend/DB/dummy/voteDummies.js
backend/DB/queries/candidate.js
backend/DB/queries/poll.js
backend/DB/queries/vote.js
backend/graphQL/model/poll/poll.graphql
backend/graphQL/model/poll/poll.resolver.js
frontend/guest-app/src/components/Poll/Item.js
frontend/guest-app/src/components/Poll/PollApollo.js
frontend/guest-app/src/components/Poll/PollCard.js
frontend/guest-app/src/components/Poll/PollContainer.js
frontend/guest-app/src/components/TabGroup/TabGroup.js

#301 
- poll, candidate, vote dummy data 생성 모듈 수정
- poll, candidate, vote sequelize 모듈 추가
- poll, candidate, vote GraphQL(Yoga) query, resolver 추가
- guest/poll 에 GraphQL(Apollo) 추가
- 실시간 투표시 socket.io server를 통한 통신
- 신규로 poll을 생성하는 기능

Feature/poll 에 GraphQL 적용

---

backend/express/app.js

hotfix: missing import GoogleStrategy at express app

---

backend/DB/dummy/pollDummies.js
backend/DB/migrations/20191112070328-create-poll.js
backend/DB/models/poll.js
backend/DB/queries/poll.js
backend/graphQL/model/poll/poll.graphql
backend/graphQL/model/poll/poll.resolver.js
backend/socket_io_server/socketHandler/Poll/createPoll.socketHandler.js
frontend/guest-app/src/components/Poll/PollApollo.js
frontend/host-app/src/components/Poll/NewPollModal.js

- state:String(10) 추가 // standby, running, closed 상태를 가짐
- duplicateOption을 allowDuplication으로 변경
- 기타: 가장 많은 득표수를 차지한 candidate의 그래프를 노랑색으로 표시함
- Poll용 socket Handler 추가 및 socket 통신을 통해 DB에 create 하는 기능 추가

enhance: Poll DB Table 필드추가/기존 필드명 변경 및 Poll 생성을 위한 socket.io 통신 추가

---

backend/DB/dummy/eventDummies.js
backend/DB/migrations/20191204794363-add-column-event.js

fix: event table에 eventName 컬럼 추가 및 더미데이터 수정

---

frontend/guest-app/src/libs/useQueryQuestions.js
frontend/host-app/src/App/App.js
frontend/host-app/src/components/Content.js
frontend/host-app/src/libs/gql.js
frontend/host-app/src/libs/useQueryQuestions.js
frontend/libs/useQueryQuestions.js

스키마 및 쿼리 변경으로 인해 host-app 뜨지 않는 문제
해결

fix: host-app 실행 가능하도록 hot-fix

---

frontend/main-app/src/components/EventForm.js
frontend/main-app/src/components/LoginModal.js
frontend/main-app/src/config/configLoader.js
frontend/main-app/src/config/env.dev.config.js
frontend/main-app/src/config/env.prod.config.js

배포용 로그인 리다이렉션 URL 추가
배포용 이벤트 참가 리다이렉션 URL 추가
개발, 배포 모드별로 env 설정을 통해 분기처리 시킴

Fix: main app deploy용 리다이렉션 url 추가

---

frontend/main-app/src/config/env.prod.config.js

hotfix: main-app 에서 guest app 으로 리다이렉트 주소

---

backend/express/app.js
backend/socket_io_server/socketHandler/Evnet/initOption.socketHandler.js
backend/socket_io_server/socketHandler/Question/questionCreate.socketHandler.js
frontend/guest-app/src/libs/useQueryQuestions.js
frontend/guest-app/src/libs/utils.js

일부 하드코딩된 eventId 가 남아있어 moderation 이 제대로
동작하지 않는 문제를 수정.
guestName 이 DB 에 빈칸으로 들어가던 문제 수정

fix: question 의 guestName이 DB 에 제대로 들어가지 않는 문제 수정

---

frontend/host-app/src/components/EventSettingModal/EventSettingTab/GeneralSetting/GeneralSetting.js
frontend/host-app/src/config/env.dev.config.js
frontend/host-app/src/config/env.prod.config.js

host link 생성 시 dev와 prod에 따라 다른 url을 추기 위해 config 추가

enhance : add url for dev,prod config

---

backend/graphQL/model/poll/pollGuest.graphql
backend/graphQL/model/poll/pollGuest.resolver.js
backend/graphQL/model/poll/pollHost.graphql
backend/graphQL/model/poll/pollHost.resolver.js
backend/socket_io_server/socketHandler/Poll/createPoll.socketHandler.js
frontend/guest-app/src/components/Poll/Item.js
frontend/guest-app/src/components/Poll/PollApollo.js
frontend/guest-app/src/components/Poll/PollContainer.js
frontend/host-app/src/components/Poll/NewPollModal.js
frontend/host-app/src/components/Poll/PollApollo.js

#301 #188
- useContext로 EventId를 얻어서 poll 가져옴
- useContext로 EventId, guestId를 얻어서 poll 가져옴
- 데모를 위해 poll state="running"으로 설정함
- Poll DB 변경에 따른 수정

Feature/poll: useContext를 이용하여 Poll 데이타를 가져오는 기능

---

backend/DB/migrations/20191209794363-add-column-event.js
backend/DB/models/event.js

hotfix: db add column at event table 

---

backend/DB/dummy/initialConfig.js
backend/DB/queries/vote.js
backend/graphQL/model/poll/pollGuest.resolver.js
backend/graphQL/model/poll/pollHost.resolver.js
backend/socket_io_server/socketHandler/Poll/notifyPollOpen.socketHandler.js
backend/socket_io_server/socketHandler/Vote/voteOff.socketHandler.js
backend/socket_io_server/socketHandler/Vote/voteOn.socketHandler.js
frontend/guest-app/src/components/Poll/PollApollo.js
frontend/guest-app/src/components/Poll/PollContainer.js
frontend/guest-app/src/components/Poll/PollReducer.js
frontend/host-app/src/components/Poll/PollContainer.js

#211 #191
- host 에서 poll을 생성하면 "대기중" 상태로 host에서만 보여짐
- "대기중" 상태인 poll의 "개시하기" 버튼을 클릭하면, "투표중"으로 상태가 변경됨
- "투표중"으로 상태가 변경된 poll은 모든 guest들에게 보여짐
- guest들간의 실시간 poll 상황이 공유됨 (복수선택 여부 지원)
- 별점매기기 투표
- guest들간의 실시간 poll 상황을 host에서도 볼 수 있게함

Feature/poll: host에서 poll 개시하면 guest에 보여줌, guest들간의 실시간 poll 상태 공유

---

backend/graphQL/model/question/question.graphql

question schema에 QuestionId가 중복되어 오류 발생, 중복을 제거하여 픽스

fix: graphql scheam 중복으로 인한 오류

---

backend/socket_io_server/socketHandler/Vote/rateOff.socketHandler.js
backend/socket_io_server/socketHandler/Vote/rateOn.socketHandler.js
frontend/guest-app/src/components/Poll/ActiveRating.js
frontend/guest-app/src/components/Poll/PollContainer.js
frontend/guest-app/src/components/Poll/PollReducer.js
frontend/host-app/src/components/Poll/PollApollo.js
frontend/host-app/src/components/Poll/PollContainer.js

#212 
- guest: 별점매기기(rating)에 대한 실시간 update
- host: 별점매기기(rating)에 대한 실시간 update
- host: N지선다(vote)에 대한 실시간 update
- host 에서 poll 종료 => closed 상태로 보여짐
- N지선다(복수선택 X) 인 상태에서 기존 record를 삭제하고 신규 record를 생성하는 DB operation을 transaction으로 처리하는 부분

Feature/poll: guest들의 실시간 poll 상태를 host 에서 볼 수 있게 함

---

backend/DB/queries/question.js
backend/socket_io_server/socketHandler/Reply/replyCreate.socketHandler.js
frontend/guest-app/src/components/Poll/PollCard.js
frontend/guest-app/src/components/Poll/PollReducer.js
frontend/guest-app/src/components/Question/QuestionCard/QuestionCard.js
frontend/guest-app/src/components/Question/QuestionContainer.js
frontend/guest-app/src/components/Question/QuestionInputArea/QuestionContentInput.js
frontend/guest-app/src/components/Question/QuestionsRepliesReducer.js
frontend/guest-app/src/components/Reply/CurrentRepliesTextField.js
frontend/guest-app/src/components/Reply/PreviewQuestion.js
frontend/guest-app/src/components/Reply/ReplierInfoInput.js
frontend/guest-app/src/components/Reply/RepliesContainer.js
frontend/guest-app/src/components/Reply/RepliesList.js
frontend/guest-app/src/components/Reply/RepliesPaper.js
frontend/guest-app/src/components/Reply/Reply.js
frontend/guest-app/src/components/Reply/ReplyArea.js
frontend/guest-app/src/components/Reply/ReplyContentInput.js
frontend/guest-app/src/components/Reply/ReplyInput.js
frontend/guest-app/src/components/Reply/ReplyInputContainer.js
frontend/guest-app/src/components/Reply/ReplyQuestionDivider.js
frontend/guest-app/src/components/Reply/useReplies.js

1. Reply View를 위한 Reply 디렉토리에 필요 컴포넌트를 구현했습니다.
2. 디비 저장을 위해 socket,query/question 부분을 약간 수정했습니다.
3. 소켓 핸들러를 하나 더만들어서 reply가 실시간으로 보이도록 수정했습니다.
4. guest front QuestionContainer 부분에 useSocket에서 Reply에 대한 디스패처도 추가했습니다.

Feature/reply Reply 기능 추가

---

backend/DB/queries/poll.js
backend/DB/queries/vote.js
backend/graphQL/model/poll/pollGuest.resolver.js
backend/socket_io_server/socketHandler/Poll/closePoll.socketHandler.js
backend/socket_io_server/socketHandler/Poll/nofityPollClose.socketHandler.js
backend/socket_io_server/socketHandler/Vote/voteOn.socketHandler.js
frontend/guest-app/src/components/Poll/Item.js
frontend/guest-app/src/components/Poll/PollApollo.js
frontend/guest-app/src/components/Poll/PollCard.js
frontend/guest-app/src/components/Poll/PollContainer.js
frontend/guest-app/src/components/Poll/PollReducer.js
frontend/host-app/src/components/Poll/Item.js
frontend/host-app/src/components/Poll/PollCard.js
frontend/host-app/src/components/Poll/PollContainer.js
frontend/host-app/src/components/Poll/RatingItem.js

#301 #212 #211 #191 #188 #68
- host 에서 poll 종료하면 host 에서 closed 상태로 보여짐
- host 에서 poll 종료하면 guest 에서 closed 상태로 보여짐
- N지선다(복수선택 X) 인 상태에서 기존 record를 삭제하고 신규 record를 생성하는 DB operation을 transaction으로 처리하는 부분

Feature/poll: Poll 마무리 작업 (guest/host, N지선다/별점매기기)

---

frontend/host-app/src/components/CreateEventModal/ButtonField.js
frontend/host-app/src/components/CreateEventModal/CreateEventModal.js
frontend/host-app/src/components/CreateEventModal/InputStartDate.js
frontend/host-app/src/components/EmptyContent.js

- 이벤트 생성문구/버튼 2개씩 보이는 것 수정
- 시작시간/종료시간 validity check로 인해 유효시간을 0 으로 다시 설정
- Hashtag 여러줄 입력시 아래 버튼 위치 조정

hotfix: (host-app) 이벤트 생성 모달 페이지 수정

---

backend/DB/queries/hashtag.js
backend/graphQL/model/hostpage/hostpage.graphql
backend/graphQL/model/hostpage/hostpage.resolver.js
frontend/host-app/src/App/App.js
frontend/host-app/src/libs/gql.js

graphql 스키마 부분에서 event를 불러올 때 hashTag 목록을 같이 불러오기 위해 schema 및 resolver를 추가.

feat: event 목록을 불러올 때 hashTag 목록을 같이 불러오도록 추가

---

backend/DB/queries/question.js
frontend/host-app/src/components/Content.js
frontend/host-app/src/components/Questions/QuestionReducer.js
frontend/host-app/src/components/useSocketHandler.js

- feat: host-guset app 간 좋아요 숫자 동기화 #401
- fix: host-app useSocket 외부 파일로 분리
- fix: host-app 상단고정 minor bug fix

Feature/guest app like sync #401

---

frontend/guest-app/src/components/Poll/PollCard.js
frontend/guest-app/src/components/Poll/PollContainer.js
frontend/host-app/src/components/Poll/PollCard.js
frontend/host-app/src/components/Poll/PollContainer.js

- (원인) 동일 브라우저이기 때문에 여러 guest들 이지만 동일한 GuestId를 갖고 있는데, 코드 상에서 GuestId가 동일하면 바로 return 하는 로직이 있기 때문
- (해결방법) 이런 경우 어쩔수없이 중복되게 state를 write 하도록 함
- (refactor 내용) DB operation 오류로 socket.io 서버에서 error를 emit 하면 별다른 처리없이 return 함
- sequelize, graphql을 거치며 pollDate의 type이 변경됨
- socket.io 를 통해서 host에서 바로 guest로 전달된 경우에는 제대로 Date가 전달됨
- 각각의 경우를 안의 내용 중 "-"가 포함되었는지를 조사하여 분기처리함 (예. "2019-12-12 ....")

Feature/poll: 동일 GuestId에 대해 상태 update 한되는 문제 해결, Date 출력 수정, 방어코드 추가

---

frontend/host-app/src/components/EventSettingModal/EventSettingTab/GeneralSetting/GeneralSetting.js

이벤트 목록에서 받아온 해시태그가 이벤트 설정모달 클릭 시 보이도록 구현

fix: 이벤트 설정 클릭 시 해시태그가 보이도록 수정

---

backend/docker/docker-product.yml
backend/libs/logger.js
backend/redis/redisClient.js

* redis client config 수정
* docker -production.yml 수정

hotfix: deploy fix

---

frontend/host-app/src/components/Poll/PollCard.js

hotfix: host 에서 standby poll 생성 후 refresh 하면 죽는 문제 수정

---

frontend/host-app/src/config/env.prod.config.js

prod.config 파일 www. 누락으로 인한 에러 ;;

fix: guest api link route 에러

---

frontend/guest-app/src/components/Poll/PollCard.js

지난 hotfix와 동일하게 pollDate에 null 값이 들어가 있는데 여기에 값이 있다고 가정하고 처리하는 루틴이 있어서 수정함
추후 DB를 보완하겠음

hotfix: host 에서 open한 poll이 guest에서 보여질때 죽는 문제 수정

---

backend/DB/queries/poll.js
backend/DB/queries/vote.js
backend/socket_io_server/socketHandler/Poll/createPoll.socketHandler.js
backend/socket_io_server/socketHandler/Vote/voteOn.socketHandler.js
frontend/guest-app/src/components/LikeButton/UndoLikeModal.js
frontend/guest-app/src/components/Poll/ActiveRating.js
frontend/guest-app/src/components/Poll/Item.js
frontend/guest-app/src/components/Poll/PollCard.js
frontend/host-app/src/components/Poll/Item.js
frontend/host-app/src/components/Poll/PollCard.js

#437
- Poll 생성시 pollDate 필드에 값을 넣어주도록 수정
- 복수선택 안되는 투표시 생성과 삭제 DB operation을 transaction으로 처리하도록 수정
- 투표 종료버튼 빨강색으로 변경
- 투표 css 수정
- 별점투표 완료 후 값 변경 안되도록 수정

Poll 관련 수정

---

backend/DB/queries/vote.js
backend/socket_io_server/socketHandler/Poll/closePoll.socketHandler.js
backend/socket_io_server/socketHandler/Poll/createPoll.socketHandler.js
backend/socket_io_server/socketHandler/Poll/nofityPollClose.socketHandler.js
backend/socket_io_server/socketHandler/Poll/notifyPollOpen.socketHandler.js
backend/socket_io_server/socketHandler/Poll/openPoll.socketHandler.js
backend/socket_io_server/socketHandler/Vote/rateOff.socketHandler.js
backend/socket_io_server/socketHandler/Vote/rateOn.socketHandler.js
backend/socket_io_server/socketHandler/Vote/voteOff.socketHandler.js
backend/socket_io_server/socketHandler/Vote/voteOn.socketHandler.js
frontend/guest-app/src/components/Poll/PollContainer.js
frontend/guest-app/src/components/Poll/PollReducer.js
frontend/host-app/src/components/Poll/PollContainer.js

- socket.io 정상 동작시에도 emit 에 status 기본으로 추가
- Vote transaction 코드로 전환
- case문 { } 로 감싸줌
- 코드 정리

Poll refactoring

---

frontend/host-app/src/components/Questions/QuestionCard/LiveQuestionCard.js
frontend/host-app/src/components/Questions/QuestionCard/ModerationQuestionCard.js

fix: merge hotfix

---

frontend/host-app/src/components/Poll/InitialPollData.js
frontend/host-app/src/components/Poll/NewPollModal.js
frontend/host-app/src/components/Poll/NewPollReducer.js
frontend/main-app/src/components/HostLoginMessage.js

- useState 대신 useReducer로 변경
- reducer를 NewPollReducer.js 로 분리
- 초기 data를 InitialPollData.js 로 분리
- 기타: main-app Google login 위치 변경

Refactor: poll

---

frontend/host-app/src/App/App.js
frontend/host-app/src/components/CreateEventModal/ButtonField.js
frontend/host-app/src/components/CreateEventModal/EndDateField.js
frontend/host-app/src/components/CreateEventModal/InputEventName.js
frontend/host-app/src/components/CreateEventModal/InputHashTag.js
frontend/host-app/src/components/Event/EventDateRage.js
frontend/host-app/src/components/EventSettingModal/EventSettingTab/GeneralSetting/EndDateField.js
frontend/host-app/src/components/EventSettingModal/EventSettingTab/GeneralSetting/InputEventCode.js
frontend/host-app/src/components/EventSettingModal/EventSettingTab/GeneralSetting/InputEventLink.js

* 호스트 앱 event 목록 시간 포맷이 달라서 생기는 오류를 moment format을 이용하여 해결

fix: 호스트앱 시간 포맷 오류

---

frontend/guest-app/src/components/SideMenu/SideMenuHeader.js

moment library 설치 후 moment format으로 변경하여 데이터 포맷이 이상하게 나오는 경우에 대해 해결

fix: guest app 데이터 포맷 오류 해결

---

frontend/guest-app/package.json
frontend/guest-app/yarn.lock

date format 설정을 위해 moment package 설치로 인한 yarn.lock, package.json 파일 수정

chore: moment package 설치로 인한 commit

---

frontend/guest-app/src/components/ReplyCard/ReplyCardList.js
frontend/guest-app/src/components/ReplyPreviewArea/ReplyPreview.js

추가로 댓글 preview 박스의 margin-bottom을 15로 변경 (기존 5)

refactor: 댓글 바탕색 gray[300]으로 변경

---

frontend/guest-app/src/components/QuestionCard/QuestionCardBody.js
frontend/host-app/src/App/App.js
frontend/host-app/src/components/Questions/QuestionCard/Replies.js
frontend/main-app/src/App.js
frontend/main-app/src/components/EventForm.js
frontend/main-app/src/components/HostLoginMessage.js

- fix: main-app minor warnings 수정
- fix: host-app 에 key 추가

fix: host-app guest-app minor warnings 제거

---

frontend/guest-app/public/manifest.json
frontend/host-app/public/manifest.json
frontend/main-app/public/manifest.json

일부 favicon 파일 삭제로 인해 경로 오류가 발생하여
mainfest 파일을 수정

fix: manifest 파일 경로로 인해 발생하는 오류 fix

---

frontend/host-app/src/App/App.js

date 타입을 비교하는 utils 함수 선언이 누락되어있어서 이를 수정.

fix: compareCurrentDateToTarget 누락으로 인한 픽스

---

frontend/guest-app/src/components/QuestionContainer/QuestionContainer.js
frontend/guest-app/src/index.css

* 아이폰 사파리에서 질문 버튼이 짤려나오는 버그 수정
-> height 속성이 누락되 잘려 나오는것이 원인
* 아이폰 사파리에서 질문 텍스트 입력이 안되는 버그 수정
-> 버튼 선택시 나오는 파란 외각선 제거 하기위한 user-select: none 이 원인

hotfix: guest-app css bug

---

frontend/host-app/src/components/NavBar/NavBar.js

fix: remove EventList

---

frontend/host-app/src/components/EventHandler/useQuestionSocketEventHandler.js
frontend/host-app/src/components/Questions/QuestionReducer.js

- fix: host-app 에서 질문 실시간 수정 안되던 bug fix
호스트 앱에서 질문수정사항이 실시간으로 반영되지 않던
버그 수정
- fix: host-app 에 질문 삭제 안되던 bug fix
host-app 에서 guest가 삭제한 질문이실시간으로
업데이트 되지 않던 버그 fix

fix: host-guest 동기화 bug fix

---

frontend/host-app/src/components/EventSettingModal/EventSettingTab/GeneralSetting/InputStartDate.js

fix: event setting 시간 설정 부분 삭제

---

frontend/guest-app/src/components/QuestionContainer/QuestionContainer.js

QuestionContainer 의 질문 버튼이 잘리는 버그 수정
guest-app의 QuestionConatiner 컴포넌트의 css 타이포 수정

hotfix: QuestionContainer 의 질문 버튼이 잘리는 버그 수정

---

backend/express/routes/guest.js
frontend/host-app/src/components/EventSettingModal/EventSettingTab/GeneralSetting/InputStartDate.js

시간과 분을 따로 계산해서 둘이 합쳐서 나오던 버그 해결

hothotfix: date type error
